In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1st step: Data Exploration & Loading

# We will load the datsets
df = pd.read_csv('Raw_Data.csv')

In [3]:
# By this we will know basic information about data
print(df.shape)

(51012, 18)

In [4]:
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Type,Gender,City,State,Country,Category,Product_Name,Quantity,Unit_Price,Discount_Amount,Shipping_Cost,Profit_Margin,Payment_Method,Delivery_Method,Order_Status
0,OR122356,25-02-2024,CUST862916,Normal,Female,Kansas City,Missouri,USA,Food & beverages,Protein Bar,4.0,$223.75,$14.63,$17.94,0.33,Cash,Store Pickup,Delivered
1,OR115321,30-12-2024,CUST125318,Normal,Female,Tonala,Jalisco,Mexico,Fashion accessories,Leather Belt,7.0,$143.96,$2.63,$13.26,0.48,Credit card,Store Pickup,Cancelled
2,OR133642,11-09-2024,CUST282162,Member,Female,Dallas,Texas,USA,Fashion accessories,Sunglasses,5.0,$167.44,$17.02,$24.61,0.09,Ewallet,Standard Delivery,Cancelled
3,OR104586,27-05-2022,CUST423735,Member,Male,Kansas City,Missouri,USA,Health & beauty,Vitamins,7.0,$78.20,$7.83,$9.01,0.20,Ewallet,Same-Day Delivery,Cancelled
4,OR111031,15-02-2023,CUST504878,Member,Male,Burnaby,British Columbia,Canada,Food & beverages,Snack Mix,3.0,$182.42,$15.08,$6.94,0.29,Credit card,Express Delivery,Cancelled

In [5]:
df.describe()

           Quantity  Profit_Margin
count  50862.000000   50835.000000
mean       4.969742       0.273741
std        2.576756       0.130016
min        1.000000       0.050000
25%        3.000000       0.160000
50%        5.000000       0.270000
75%        7.000000       0.390000
max        9.000000       0.500000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51012 entries, 0 to 51011
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_Id         51012 non-null  object
 1   Order_Date       51012 non-null  object
 2   Customer_Id      51012 non-null  object
 3   Customer_Type    51012 non-null  object
 4   Gender           51012 non-null  object
 5   City             51012 non-null  object
 6   State            51012 non-null  object
 7   Country          51012 non-null  object
 8   Category         51012 non-null  object
 9   Product_Name     51012 non-null  object
 10  Quantity         50862 non-null  float64
 11  Unit_Price       50833 non-null  object
 12  Discount_Amount  51012 non-null  object
 13  Shipping_Cost    51012 non-null  object
 14  Profit_Margin    50835 non-null  float64
 15  Payment_Method   51012 non-null  object
 16  Delivery_Method  51012 non-null  object
 17  Order_Status     51012 non-null  object
dtypes: float64(2), object(16)
memory usage: 7.0+ MB

In [7]:
df.isnull().sum()

Order_Id             0
Order_Date           0
Customer_Id          0
Customer_Type        0
Gender               0
City                 0
State                0
Country              0
Category             0
Product_Name         0
Quantity           150
Unit_Price         179
Discount_Amount      0
Shipping_Cost        0
Profit_Margin      177
Payment_Method       0
Delivery_Method      0
Order_Status         0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(200)

In [9]:
df.dropna(inplace=True)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
print("Raw Data Shape:", df.shape)

Raw Data Shape: (50306, 18)

In [12]:
df.dtypes

Order_Id            object
Order_Date          object
Customer_Id         object
Customer_Type       object
Gender              object
City                object
State               object
Country             object
Category            object
Product_Name        object
Quantity           float64
Unit_Price          object
Discount_Amount     object
Shipping_Cost       object
Profit_Margin      float64
Payment_Method      object
Delivery_Method     object
Order_Status        object
dtype: object

In [13]:
# 2nd step: Data cleaning 

df['Category'] = df['Category'].str.strip()

In [14]:
finance_columns = ['Unit_Price', 'Discount_Amount', 'Shipping_Cost']
for col in finance_columns:
    df[col] = df[col].astype(str).str.replace('$', '', regex=False).astype(float)
# by this we removed '$' and coverted the price which was object data type to float data type

In [15]:
df.dtypes

Order_Id            object
Order_Date          object
Customer_Id         object
Customer_Type       object
Gender              object
City                object
State               object
Country             object
Category            object
Product_Name        object
Quantity           float64
Unit_Price         float64
Discount_Amount    float64
Shipping_Cost      float64
Profit_Margin      float64
Payment_Method      object
Delivery_Method     object
Order_Status        object
dtype: object

In [16]:
# 3rd step: Data Transformation (We will be Adding new columns logically)

df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%d-%m-%Y', errors='coerce')
df['Order_Year'] = df['Order_Date'].dt.year
df['Order_Quarter'] = 'Q' + df['Order_Date'].dt.quarter.astype(str)
df['Order_Month'] = df['Order_Date'].dt.month_name().str[:3] 
df['Day_Of_Week'] = df['Order_Date'].dt.day_name()

In [17]:
df.head()

,Order_Id,Order_Date,Customer_Id,Customer_Type,Gender,City,State,Country,Category,Product_Name,...,Discount_Amount,Shipping_Cost,Profit_Margin,Payment_Method,Delivery_Method,Order_Status,Order_Year,Order_Quarter,Order_Month,Day_Of_Week
0,OR122356,2024-02-25,CUST862916,Normal,Female,Kansas City,Missouri,USA,Food & beverages,Protein Bar,...,14.63,17.94,0.33,Cash,Store Pickup,Delivered,2024,Q1,Feb,Sunday
1,OR115321,2024-12-30,CUST125318,Normal,Female,Tonala,Jalisco,Mexico,Fashion accessories,Leather Belt,...,2.63,13.26,0.48,Credit card,Store Pickup,Cancelled,2024,Q4,Dec,Monday
2,OR133642,2024-09-11,CUST282162,Member,Female,Dallas,Texas,USA,Fashion accessories,Sunglasses,...,17.02,24.61,0.09,Ewallet,Standard Delivery,Cancelled,2024,Q3,Sep,Wednesday
3,OR104586,2022-05-27,CUST423735,Member,Male,Kansas City,Missouri,USA,Health & beauty,Vitamins,...,7.83,9.01,0.20,Ewallet,Same-Day Delivery,Cancelled,2022,Q2,May,Friday
4,OR111031,2023-02-15,CUST504878,Member,Male,Burnaby,British Columbia,Canada,Food & beverages,Snack Mix,...,15.08,6.94,0.29,Credit card,Express Delivery,Cancelled,2023,Q1,Feb,Wednesday

In [18]:
df['Base_Price'] = df['Quantity'] * df['Unit_Price']

In [19]:
df['Net_Sales'] = df['Base_Price'] - df['Discount_Amount']

In [20]:
df['Tax'] = df['Net_Sales'] * 0.08 
# I Take 8% standardized tax rate across all item to keep data model simple

In [21]:
df['Total_Amount'] = df['Net_Sales'] + df['Tax'] + df['Shipping_Cost']

In [22]:
df[['Base_Price', 'Net_Sales', 'Tax', 'Total_Amount']] = df[['Base_Price', 'Net_Sales', 'Tax', 'Total_Amount']].round(2)
# Rounding these columns to 2 decimal places for neatness

In [23]:
# 4th step: Data Restructuring

df['Order_Status'] = df['Order_Status'].replace({'Processing': 'Delivered'})

In [24]:
df.columns

Index(['Order_Id', 'Order_Date', 'Customer_Id', 'Customer_Type', 'Gender',
       'City', 'State', 'Country', 'Category', 'Product_Name', 'Quantity',
       'Unit_Price', 'Discount_Amount', 'Shipping_Cost', 'Profit_Margin',
       'Payment_Method', 'Delivery_Method', 'Order_Status', 'Order_Year',
       'Order_Quarter', 'Order_Month', 'Day_Of_Week', 'Base_Price',
       'Net_Sales', 'Tax', 'Total_Amount'],
      dtype='object')

In [25]:
new_column_order = ['Order_Id', 'Order_Date', 'Order_Year', 'Order_Quarter', 'Order_Month', 'Day_Of_Week', 
                    'Customer_Id', 'Customer_Type', 'Gender', 'City', 'State', 'Country',
                    'Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Base_Price',
                    'Discount_Amount', 'Tax', 'Shipping_Cost', 'Net_Sales', 'Total_Amount', 'Profit_Margin',
                    'Payment_Method', 'Delivery_Method', 'Order_Status'] 

df = df[new_column_order]

In [26]:
df.head()

,Order_Id,Order_Date,Order_Year,Order_Quarter,Order_Month,Day_Of_Week,Customer_Id,Customer_Type,Gender,City,...,Base_Price,Discount_Amount,Tax,Shipping_Cost,Net_Sales,Total_Amount,Profit_Margin,Payment_Method,Delivery_Method,Order_Status
0,OR122356,2024-02-25,2024,Q1,Feb,Sunday,CUST862916,Normal,Female,Kansas City,...,895.00,14.63,70.43,17.94,880.37,968.74,0.33,Cash,Store Pickup,Delivered
1,OR115321,2024-12-30,2024,Q4,Dec,Monday,CUST125318,Normal,Female,Tonala,...,1007.72,2.63,80.41,13.26,1005.09,1098.76,0.48,Credit card,Store Pickup,Cancelled
2,OR133642,2024-09-11,2024,Q3,Sep,Wednesday,CUST282162,Member,Female,Dallas,...,837.20,17.02,65.61,24.61,820.18,910.40,0.09,Ewallet,Standard Delivery,Cancelled
3,OR104586,2022-05-27,2022,Q2,May,Friday,CUST423735,Member,Male,Kansas City,...,547.40,7.83,43.17,9.01,539.57,591.75,0.20,Ewallet,Same-Day Delivery,Cancelled
4,OR111031,2023-02-15,2023,Q1,Feb,Wednesday,CUST504878,Member,Male,Burnaby,...,547.26,15.08,42.57,6.94,532.18,581.69,0.29,Credit card,Express Delivery,Cancelled

In [27]:
# 5th step: saving the file and formating it for mysql compatiblility

df.columns = df.columns.str.lower()

In [28]:
df.to_csv('Walmart_Cleaned_Data.csv', index=False)
print("Data cleaning complete. Saved as Walmart_Cleaned_Data.csv")

Data cleaning complete. Saved as Walmart_Cleaned_Data.csv

In [29]:
df.describe(include='all')

,order_id,order_date,order_year,order_quarter,order_month,day_of_week,customer_id,customer_type,gender,city,...,base_price,discount_amount,tax,shipping_cost,net_sales,total_amount,profit_margin,payment_method,delivery_method,order_status
count,50306,50306,50306.000000,50306,50306,50306,50306,50306,50306,50306,...,50306.000000,50306.000000,50306.000000,50306.000000,50306.000000,50306.000000,50306.000000,50306,50306,50306
unique,50306,NaN,NaN,4,12,7,48911,2,2,25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,4,3
top,OR145962,NaN,NaN,Q4,Oct,Saturday,CUST148117,Member,Male,Kansas City,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Store Pickup,Cancelled
freq,1,NaN,NaN,12780,4413,7320,3,25300,25289,7222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16845,12642,16907
mean,NaN,2023-07-02 00:08:31.811712512,2022.999602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,780.000147,18.602591,60.911804,14.969205,761.397555,837.278564,0.273677,NaN,NaN,NaN
min,NaN,2022-01-01 00:00:00,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,545.220000,0.000000,37.310000,5.000000,466.390000,511.640000,0.050000,NaN,NaN,NaN
25%,NaN,2022-10-02 00:00:00,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,662.570000,5.750000,51.740000,9.960000,646.762500,713.545000,0.160000,NaN,NaN,NaN
50%,NaN,2023-07-02 00:00:00,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,780.765000,11.540000,60.950000,14.930000,761.835000,837.700000,0.270000,NaN,NaN,NaN
75%,NaN,2024-03-31 00:00:00,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,898.110000,21.570000,70.000000,19.990000,875.060000,960.207500,0.390000,NaN,NaN,NaN
max,NaN,2024-12-31 00:00:00,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1012.550000,148.430000,80.950000,25.000000,1011.840000,1114.610000,0.500000,NaN,NaN,NaN
std,NaN,NaN,0.815099,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,135.097293,21.866090,10.688301,5.777501,133.603909,144.392905,0.129981,NaN,NaN,NaN